module.exports = {
  ALREADY_EXIST: "Account already exist",
  SIGNUP_SUCCESS: "Account created successfully",
  ACCOUNT_NOT_EXIST: "Account not exist with this email",
  SIGNUP_FAILE: "Error occur while creating account",
  LOGIN_SUCCESS: "Login successfully",
  INVALID_CREDENTIAL: "Invalid credentials",
  OTP_SEND: "OTP send on your email",
  OTP_ERROR: "Error occur while sending OTP",
  OTP_VERIFY_SUCCESS: "OTP verified successfully",
  INVALID_OTP: "Invalid OTP",
  OTP_EXPIRE: "OTP expire",
  PASSWORD_NOT_MATCH: "Password not match with confirm password",
  OLD_PASSWORD_MATCH: "Password can't be same as old password",
  OLD_PASSWORD_NOT_MATCH: "Old password not match",
  PASSWORD_RESTORE_SUCCESS: "Password restore successfully",
  PASSWORD_RESTORE_ERROR: "Password restore failed",
  CHANGE_PASSWORD_SUCCESS: "Password changed successfully",
  CHANGE_PASSWORD_ERROR: "Password changed failed",
  VERIFY_OTP_MESSAGE: "Account not verify",
  ALREADY_SUBSCRIBE: "Already subscribed LoCostore",
  SUBSCRIBE_SUCCESS: "LoCostore subscribed successfully",
  SOMETHING_WRONGE: "Something went wronge",
  PRODUCT_EXIST: "Product already exist",
  PRODUCT_SAVE: "Product added successfully",
  PRODUCT_ERROR: "Product added failed",
  PRODUCT_FOUND_SUCCESS: "Product found successfully",
  PRODUCT_FOUND_ERROR: "Product not found",
  PRODUCT_DETAILS_SUCCESS: "Product details found successfully",
  PRODUCT_DETAILS_ERROR: "Product details not found",
  PRODUCT_UPDATE_SUCCESS: "Product updated successfully",
  PRODUCT_UPDATE_ERROR: "Product not updated",
  PRODUCT_DELETE_SUCCESS: "Product deleted successfully",
  PRODUCT_DELETE_ERROR: "Product deleted failed",
  PRODUCT_STATE_UPDATE_FAILED: "Product state update failed",
  EMAIL_LOG_SUCCESS: "Email log found successfully",
  EMAIL_LOG_ERROR: "Email log not found",
  EMAIL_LOG_DELETE_SUCCESS: "Email log deleted successfully",
  EMAIL_LOG_DELETE_ERROR: "Email log delete failed",
  USER_LIST_FOUND: "User list found successfully",
  USER_LIST_NOT_FOUND: "User list not found",
  USER_DETAILS_FOUND: "User details found successfully",
  USER_DETAILS_NOT_FOUND: "User details not found",
  USER_DELETE_SUCCESS: "User deleted successfully",
  USER_DELETE_ERROR: "User deleted failed",
  USER_STATEID_ACTIVE_SUCCESS: "User active successfully",
  USER_STATEID_BAN_SUCCESS: "User ban successfully",
  USER_STATEID_UPDATE_ERROR: "User stateId not updated",
  BAN_MESSAGE: "Your account is ban please contact admin",
  CONTACTUS_SAVE_SUCCESS: "Thankyou for contacting us. we mail you shortly",
  CONTACTUS_SAVE_ERROR: "Contact us failed",
  CONTACTUS_LIST_FOUND: "Contact list found successfully",
  CONTACTUS_LIST_NOT_FOUND: "Contact list not found",
  CONTACTUS_DETAILS_FOUND: "Contact details found successfully",
  CONTACTUS_DETAILS_NOT_FOUND: "Contact details not found",
  PROFILE_UPDATE_SUCCESS: "Profile updated successfully",
  PROFILE_UPDATE_ERROR: "Profile updated failed",
  PROFILE_VIEW_SUCCESS: "Profile view successfully",
  PROFILE_VIEW_ERROR: "Profile view failed",
  CONTACTUS_MARKED_SUCCESS: "Contactus marked completed",
  CONTACTUS_MARKED_ERROR: "Contactus marked failed",
  CONTACTUS_DELETE_SUCCESS: "Contactus deleted successfully",
  CONTACTUS_DELETE_ERROR: "Contactus deleted failed",
  CATEGORY_EXIST: "Category already exist",
  CATEGORY_ADD_SUCCESS: "Category added successfully",
  CATEGORY_ADD_ERROR: "Category added failed",
  CATEGORY_UPDATE_SUCCESS: "Category update successfully",
  CATEGORY_UPDATE_ERROR: "Category update failed",
  CATEGORY_LIST_SUCCESS: "Category list found successfully",
  CATEGORY_LIST_ERROR: "Category list not found ",
  CATEGORY_DETAILS_SUCCESS: "Category details found successfully",
  CATEGORY_DETAILS_ERROR: "Category details not found",
  CATEGORY_ACTIVE: "Category active successfully",
  CATEGORY_NOT_ACTIVE: "Category  active failed",
  CATEGORY_INACTIVE: "Category inactive successfully",
  CATEGORY_NOT_INACTIVE: "Category inactive failed",
  CATEGORY_DELETE_SUCCESS: "Category deleted successfully",
  CATEGORY_DELETE_ERROR: "Category deleted failed",
  LOGIN_ACTIVITY_FOUND: "Login activity list found successfully",
  LOGIN_ACTIVITY_NOT_FOUND: "Login activity list not found",
  LOGIN_ACTIVITY_DETAILS_SUCCESS: "Login activity details found",
  LOGIN_ACTIVITY_DETAILS_ERROR: "Login activity details not found",
  LOGIN_ACTIVITY_DELETE_SUCCESS: "Login activity deleted successfully",
  LOGIN_ACTIVITY_DELETE_ERROR: "Login activity delete failed",
  CMS_EXIST: "CMS already exist with this type",
  CMS_ADDED_SUCCESS: "CMS added successfully",
  CMS_ADDED_ERROR: "CMS added failed",
  CMS_LIST_SUCCESS: "CMS list found successfully",
  CMS_LIST_ERROR: "CMS list not found",
  CMS_EDIT_SUCCESS: "CMS updated successfully",
  CMS_EDIT_ERROR: "CMS update failed",
  CMS_FOUND_SUCCESS: "CMS details found successfully",
  CMS_FOUND_ERROR: "CMS deatils not found",
  CMS_DELETE_SUCCESS: "CMS deleted successfully",
  CMS_DELETE_ERROR: "CMS delete failed",
  CMS_STATEID_ACTIVE_SUCCESS: "CMS active successfully",
  CMS_STATEID_INACTIVE_SUCCESS: "CMS inactive successfully",
  CMS_STATEID_UPDATE_ERROR: "CMS stateId not updated",
  ADDRESS_EXIST: "Address already exist",
  ADDRESS_SAVE_SUCCESS: "Address added successfully",
  ADDRESS_SAVE_ERROR: "Address add failed",
  ADDRESS_LIST_SUCCESS: "Address list found successfully",
  ADDRESS_LIST_ERROR: "Address list not found",
  ADDRESS_DELETE_SUCCESS: "Address deleted successfully",
  ADDRESS_DELETE_ERROR: "Address delete failed",
  ADDRESS_DETAILS_SUCCESS: "Address details found successfully",
  ADDRESS_DETAILS_ERROR: "Address details not found",
  ADDRESS_UPDATE_SUCCESS: "Address updated successfully",
  ADDRESS_UPDATE_ERROR: "Address update failed",
  ADDRESS_DEFAULT_SUCCESS: "Address set as default successfully",
  ADDRESS_DEFAULT_ERROR: "Address not set as default",
  FAQ_EXIST: "FAQ already exist",
  FAQ_SAVE_SUCCESS: "FAQ added successfully",
  FAQ_SAVE_ERROR: "FAQ add failed",
  FAQ_UPDATED_SUCCESS: "FAQ updated successfully",
  FAQ_UPDATED_ERROR: "FAQ updated failed",
  FAQ_DETAILS_SUCCESS: "FAQ details found successfully",
  FAQ_DETAILS_ERROR: "FAQ details not found",
  FAQ_DELETE_SUCCESS: "FAQ deleted successfully",
  FAQ_DELETE_ERROR: "FAQ delete failed",
  FAQ_LIST_SUCCESS: "FAQ list found successfully",
  FAQ_LIST_ERROR: "FAQ list not found",
  FAQ_STATEID_ACTIVE_SUCCESS: "FAQ active successfully",
  FAQ_STATEID_INACTIVE_SUCCESS: "FAQ inactive successfully",
  FAQ_STATEID_UPDATE_ERROR: "FAQ stateId not updated",
  CART_ADD_SUCCESS: "Product added in cart",
  CART_ADD_ERROR: "Product added in cart failed",
  CART_LIST_SUCCESS: "Cart list successfully",
  CART_LIST_ERROR: "Cart list found failed",
  CART_REMOVE_SUCCESS:"Cart remove successfully",
  CART_REMOVE_FAILED:"Cart remove failed",

};
